// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://clbpctebxsygstxupcss.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNsYnBjdGVieHN5Z3N0eHVwY3NzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2NDAwODQsImV4cCI6MjA2NzIxNjA4NH0.LHozkvK2vsqEQMATOzdk8NP5sqP6PKNtetOm24lwWcs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});